# Generated by Django 4.1.7 on 2023-03-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36)),
                ("time", models.IntegerField()),
                ("board", models.CharField(max_length=500)),
            ],
        ),
    ]
