# Generated by Django 4.1.7 on 2023-03-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chessapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardinstance",
            name="uuid",
            field=models.CharField(max_length=1000),
        ),
    ]
